var uiText = {
	//interfaces.pck/npc_talk.stf
	66225: "\r^ffcb4aPrincess Moondreamer of the Luneska City possessed some of the Frost Emperor's courageous power. \rEven though born in Luneska City, she was not a great warrior like her sister.\rJust like her name suggested, she was a dreamer and tender woman. \rShe took great priorities in her relationship with her sister, but for \rthe safety of the Luneska City, she helped the adventurers defeat Princess Moonhowler.\r\r^ffffff",
	66226: "\rPlace of Origin Bond: Luneskan Radianace\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66227: "\r^ffcb4aThe Jaden Collector from Archosaur City \ris a lesser celestial being who travels around \rthe world and trades with others the artifacts \rhe found during this travels. He is not a great \rfighter himself, yet he has a pair of keen eyes, \rthat the artifacts he found are popular \ramongst the adventurers. Wherever he goes, \rpeople are willing to help him.\r\r^ffffff",
	66228: "\r^ffcb4aThe Shoka Captain Tooma from Shoka \rSanctuary in the Primal World walks with four \rlegs. He has dragon claws and serpent tails, \rand his colorful crown can both charm and \rintimidate others. Tooma has been fighting \rthe City of Tideswell for long, and has \rconfronted Rowan for quite a few times. \rThe two are in even match, but due to the fact that \rRowan is better in leadership, Tooma's \rforces always falls disadvantageous. Tooma never \rgives up from his defeats, and keeps trying \rto find a way to come back.\r\r^ffffff",
	66229: "\r^ffcb4aNexus of Luminance Tactician Mur from \rMorai was the mind behind the Luminance \rforces. Be it combat operations and logistics, \rhe managed the tasks with impeccable \refficiency. Don't underestimate his lethality just \rbecause he is a tactician. He in fact is a \rgreat magic user himself. One of his greatest \rfeat was that he summoned flame from the \rheavens, and singlehandedly captured the \renemy commander.\r\r^ffffff",
	66230: "\r^ffcb4aThe Shroud Craftsman from the Shrouded \rTemple in Morai was a pillar to the Shroud \rforces. He is in charge of the development and \rmanufacture of weapons. Normally, Yurin \rwould not become a leader of the Shroud, \rbecause they are always researchers of the \rarcane. However, due to the open conflict \rbetween the Morai factions, the Shroud had to \rkeep an army of its own, and that gives Yurin \rthe chance to enact his strength\r\r^ffffff",
	66231: "\r^ffcb4aThe Corona King from Corona Sanctuary \rin Morai is the leader and founder of the \rCorona faction. He masters the key that \rconnects time and space, and possesses great \rknowledge and magic power. Kisian always \rtasks himself to uphold justice and maintain \rthe peace. He believes that the other two \rfactions should not interfere with heavenly ways, \rso even he despises it, he has to fight and \rstop them.\r\r^ffffff",
	66232: "\r^ffcb4aPrincess Moonhowler of the Luneska City \rpossesses great Frost Emperor power. \r\rBorn in Luneska City, she was a brave and \rfierce warrior. \rShe turned her back on her \rsister for her love and ideal, and lost control \rto her desired. In the end, she was utterly \rdefeated. \r\r^ffffff",
	66233: "\r^ffcb4aThe Ice Core Archon of Glacier City who \ris in charge of managing the power in Glacier \rCity. He is obsessed with the Power of the \rNorthern Realm. It may be for the people of the \rGlacier City to life a better life, or may be \rfor a certain woman. \r\r^ffffff",
	66234: "\r^ffcb4aThe Mad Princess of Flowsilver Palace remained \rfaithful to her husband Mushi, even \rthough she was cast out and imprisoned in this cold \rchamber. Her name was Belle Leun, \rand used to be a kind and merciful woman. Her love \rfor Mushi drove her mad, and she \rcould do anything for him.\r\r^ffffff",
	66235: "\r^ffcb4aThe Incantation Master of the Arcane Academy \rin the city of Neverfall. He masters a \rlot of powerful spells that can take away the \rlives of his enemies in a snap of his fingers. \rHe claims that he has a lot of talented students, \rone of which being Lily. Frizar rarely uses \rhis powerful spells, because he believes that \rthe purpose of magic is to make people's life \rbetter. \r\r^ffffff",
	66236: "\r^ffcb4aDynia is the deputy commander of the \rRose Cavalry legion of the city of Neverfall. \rShe is proud of being one of the Rose Cavalry, \rand the Rose Cavalry is proud of having \rher. Dynia aimed to become a Rose Cavalier since \rshe was young, and with hardworking \rand perseverance, she managed to fulfill her dream. \rShe has become the number one \rCavalier and the only female leader. She is still fighting \rfor her ideal, as well as the glory of \rthe Rose Cavalry.\r\r^ffffff",
	66237: "\r^ffcb4aAstrology Master of the Arcane Academy \rof the city of Neverfall. She possesses the \rpower to predict the future, and keeps providing \rprecious advises to the leadership of the \rcity. Even though these prophecies are foretold \rin her dreams, it still proves that Angelina \rwas greatly talented. Angelina teaches Divination \rcourses. A few students always believe \rshe is a liar, so they never show up in her classes.\r\r^ffffff",
	66238: "\r^ffcb4aRowan is the guard commander of the City \rof Tideswell in the Primal World. He \rdefends the city with the Castellan Hydro, and \rserves as the pillar of the community. He is \ralways at the frontline in the war against the \rShoka army, and has never suffered a defeat. \rHe is most like to be elected as the next \rCastellan of the City of Tideswell.\r\r^ffffff",
	66239: "\r^ffcb4aShroud Prophet at the Shrouded Temple \rin Morai. He masters unpredictable magic \rspells and can travel between different dimensions. \rHe is also the leader of the Shroud who \rrules with a determined ironfist. Mogo always \rsays that he created the Shroud to reveal the \rsecrets of the universe. The Shroud never wants \rto conflict with the other two factions. \rHowever, from what he does currently, his goal is \rnothing else but achieving immortality.\r\r^ffffff",
	66240: "\r^ffcb4aVyn Yen from the Archosaur City is a \rdescendant of the Elysium. He has a \rmysterious background, and can use his power \rto create a world of its own. He can convert \rall sorts of artifacts acquired from Elysium into \rmaterials used to craft the weapons of the \rSixteen Lords of  Elysium. That makes people \rsuspicious about his relationship with the \rSixteen Lords of Elysium. However, he never \rreveals anything about himself, and no one \rwants to investigate anymore. \r\r^ffffff",
	66241: "\r^ffcb4aThe War School Archon of Glacier City, \rwho masters the martial force of the Glacier \rCity. She has fought in a thousand battles \rand was never defeated. Any new soldiers \renlisted in Glacier City will have to past her \rtrials. Anyone who can win her recognition will \rbe regarded as a great warrior, which is the \rtopmost honor in the Glacier City.\r\r^ffffff",
	66242: "\r^ffcb4aThe Hand of Gold and Silver Archon of \rthe Glacier City, who controls the economy of \rthe Glacier City. Gabriel can crease all commercial \ractivities in the Glacier City with one \rword, but he would never do such a thing as \rit is against the interest of the Glacier City. \rAfter all, the goal of the three Archons is to maintain \rthe power and peace of the Glacier City.\r\r^ffffff",
	66243: "\r^ffcb4aThe grand marshal of the city of Archosaur \rwho was a great army commander as well \ras a fierce warrior himself. He enjoys great fame \rand respect in the city of Archosaur, and \rperformed extraordinarily in battles against \rinvaders. He also led the army of Archosaur \rCity to outlying territories to aid them in their \rbattles. His name is heard, feared, and \rrespected all across he Perfect World.\r\r^ffffff",
	66244: "\r^ffcb4aCandersis is the commander of the Rose \rCavalry of the city of Neverfall. He is a loyal \rfollower and guard to Alexander the Light Emperor. \rHe always leads the Rose Cavalry in \rthe front line to defend the city of Neverfall, and \rhas never given his enemies even the \rslightest chance to win. However, his top priority \ris not to defend the city, but to protect \rAlexander the Light Emperor.\r\r^ffffff",
	66245: "\r^ffcb4aThe grand marshal of the city of Archosaur \rwho was a great army commander as well \ras a fierce warrior himself. He enjoys great fame \rand respect in the city of Archosaur, and \rperformed extraordinarily in battles against \rinvaders. He also led the army of Archosaur \rCity to outlying territories to aid them in their \rbattles. His name is heard, feared, and \rrespected all across he Perfect World.\r\r^ffffff",
	66246: "\r^ffcb4aConjuration Master of the Arcane Academy \rin the city of Neverfall. He can summon \rcreatures from the other dimensions to aid him, \rand thus turn the tide of the battle. Magnus \ronly summons a cute little creatures in his \rclasses. He thinks this would be enough for his \rstudents to master. After all, some students \rhave caused troubles before.\r\r^ffffff",
	66247: "\r^ffcb4aShelly from the Glacier City is a clever \rand brave young man. He is a good person in \rnature, but he also has to complete his \rassignment as a spy for the Frost Emperor. He \rworked his way between the three factions \rthat contend with each other for the Power of \rthe Northern Realm, and tried his best to \rprotect the one he holds dearest.\r\r^ffffff",
	66248: "\r^ffcb4aHydro is the Castellan of the City of Tideswell \rin Primal World, who has kept the city \rsafe and stable in the turbulent waters. He had \rbeen fighting against the Shoka armies \rsince a very young age, and his feats earned \rhim the title of the Castellan.\r\r^ffffff",
	66249: "\r^ffcb4aThe headmaster of the Arcane Academy \rin the city of Neverfall. He masters all the \rmagic spell in Neverfall, and has trained a lot \rof powerful mages. Khafasha is extremely \rwise, as much as he is old. No one knows he \rhas lived for how long. They only know that \rthe headmaster knows everything that happened \rin Perfect World as if he was part of it.\r\r^ffffff",
	66250: "\r^ffcb4aAstarina from the Glacier City is the \rdescendant of the power of the Frost Emperor. \rWhen unleashed, her power is much stronger \rthan she herself can control. Astarina is \rcheerful and easygoing. She is brave enough \rto face any difficulty. However, she can be \rreckless sometimes, and makes a lot of \rmistakes for being less thoughtful.\r\r^ffffff",
	66251: "\r^ffcb4aThe Lord Tyrant of the Flowsilver Palace \rwas once a great ruler in the Primal World \rwho had created a powerful empire in the \rgod-forsaken Primal World. However, his violent \rnature took the better of him, and people \rstarted to rebel against him. Eventually, he was \roverthrown, and was called a Tyrant ever \rsince.\r\r^ffffff",
	66252: "\r^ffcb4aThe chief executive of the City Hall in Neverfall. \rHe always dreams of helping \rNeverfall to become great again, and has always \rbeen working hard toward that goal. \rMichael almost handles all the administration \rworks singlehandedly, and is the main reason \rthat keeps Neverfall a dominant city in \rWestern Continent. \r\r^ffffff",
	66253: "\r^ffcb4aCommander of the Nexus of Luminance in \rMorai. Gugg is arrogant and powerful, and \ris in control of a strong army. He has been \rkeeping the balance between the three factions \rof Morai. In Gugg's eyes, balance is the source \rof everything. Once the world loses \rbalance, it will degenerate into a living hell, \rwhere all beings would fall into chaotic \rmadness. Even though he claims that he does \reverything to keep balance, no one knows \rhis true intentions. \r\r^ffffff",
	66254: "\r^ffcb4aKyno in Corona Sanctuary in Morai was extremely \rtalented when he was young, and \rhas become an important member of the Corona \rforce. The legend says that when he was \rborn, the sky was clouded in all colors. When he \rgrew up, a light aura started to glow \raround him. Then, the Corona King showed up and \rbrought him to the Corona Sanctuary.\r\r^ffffff",
	66255: "\rPlace of Origin Bond: Glacier Power\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66256: "\rPlace of Origin Bond: Tideswell Wave\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66257: "\rPlace of Origin Bond: Archosaur Morale\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66258: "\rPlace of Origin Bond: Morai Mirage\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66259: "\rPlace of Origin Bond: Neverfall Light\r^b0b0b0Triggered when the Cultivation Trait of current \rPlace of Origin has the highest Star \rGrade in the Spirit Branch^ffffff",
	66260: "\rPlace of Origin Bond: Flowsilver Anger\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this place of origin to trigger the effect^ffffff",
	66261: "\rPlace of Origin Bond: Magical Energy\r^b0b0b0Requires only (1) Cultivation Traits from this place of origin \rin the Spirit Branch to trigger the effect^ffffff",
	66262: "\rPlace of Origin Bond: Earth Vein\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this class in the Spirit Branch to trigger the effect^ffffff",
	66263: "\rPlace of Origin Bond: Wisdom Light\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this class in the Spirit Branch to trigger the effect^ffffff",
	66264: "\rPlace of Origin Bond: Loyalty\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this class in the Spirit Branch to trigger the effect^ffffff",
	66265: "\rPlace of Origin Bond: Lethal Frenzy\r^b0b0b0Requires at lease (N) different Cultivation Traits \rfrom this class in the Spirit Branch to trigger the effect^ffffff",
	
	//interfaces.pck/ingame.stf
	18385: "Growth Time: %d/%d Days",
	18386: "Growth Point: %d",
	18387: "%d G",
	18388: "Zenith Pool Level: %d",
	18389: "^ff0000%d G",
	18390: "Potential Owned: %dG",
	18391: "(%dG)",
	18392: "(Free)",
	18393: "Upgrade Zenith Pool (%dG)",
	18394: "^ff0000Upgrade School (%dG)",
	18395: "Zenith Pool Upgrade: %d/%d",
	18396: "Insufficient Potential. Unable to purchase",
	18397: "%d%% chance is increased by an additional %d",
	18398: "Cultivation Bonus +%d\rBond Bonus +%d",
	18400: "Advent of the Celestial Infant",
	18401: "^ffffff",
	18402: "^8080ff",
	18403: "^aa32ff",
	18404: "^ffdc50",
	18405: "^ff0000",
	18410: "(%d) %s:",
	18411: "Cultivation Traits of the same type (Same place of origin or same class)\r",
	18412: "All Cultivation Traits in the Spirit Branch\r",
	18413: "Cultivation Trait in the Spirit Branch with the most Growth Points\r",
	18420: "Increase Growth Points by %d%%^ffffff",
	18421: "(N) The City of Neverfall: When its Star Grade is the highest in the Spirit Branch, \rincreases Growth Points by %d%%^ffffff",
	18422: "(1) Arcane Academy: When you have equiped only %d %s Cultivation Traits, \r%s will increase Growth Points by %d%%^ffffff",
	18423: "Growth Point %d",
	18424: "Sell: %d G",
	18425: "Level: %d",
	18426: "Total Level: %d",
	18427: "Withdrawal failed. The old gear has been fused with a Twilight Soul.\rPlease remove the Twilight Soul first.",
	18428: "You can use %d Potential to purchase %d Zenith Pool EXP\rCurrent Zenith Pool Level: ",
	18429: "           When Tutoring is completed, nothing more can be done for the rest of the day.\r              Potential already gained will be cleared at 24:00\rThis Tutoring action will increase Infant's Growth Points by ^ff0000%d^ffffff. Do you want to proceed?",
	18430: "Starting a new day will increases Zenith Pool EXP by %d",
	18431: "You have reached maximum number of Fashion sets. Unable to add",
	18432: "Insufficient Silver Coins. Do you want to convert %I64d Gold Coins to level up?",
	18433: "^ffffffRequires Celestial Infant Level: %d",
	18434: "%s Zenith Pool LV%d. The chance for Cultivation Traits of different qualities to spawn is %s",
	18435: "When Tutoring, there is a %d%% chance to \r",
	18440: "Deleting Battlefield: %d. Do you want to confirm?",
	18441: "Arrange a match for Red Team: %s and Blue Team: %s. Do you want to proceed?",
	18442: "The match is canceled",
	18443: "A cancel message will be sent to players whose Preparation Chamber is deleted. Do you want to proceed?",
	18444: "Preparation Completed",
	18445: "The match is canceled. Match results are not calculated.",
	18446: "The teams have incorrect number of players. The match is canceled",
	18447: "Preparation Completed. Squads ready ^00ff00%d/%d",
	18448: "Teammate ^00ff00%s^bed293 is ready. Squads ready ^00ff00%d/%d",
	18449: "Paused %02d:%02d",
	18450: "The match is about to start",
	18451: "Teammate ^00ff00%s^bed293 canceled Preparation and logged off. Squads ready ^00ff00%d/%d",
	18452: "All currently ongoing matches will be paused. \rAll matches that have not started will be canceled.\rAll Preparation Chambers will be removed.\rDo you confirm?",
	18453: "The match will resume in 10 seconds. Do you want to confirm?",
	18454: "Match paused. Please restore normal time first.",
	18455: "Paused. Unable to complete this action.",
	18456: "Please sync time first",
	18457: "Please wait for all matches to end and then sync time",
	18458: "There is no ongoing match. Unable to pause.",
	18460: "^ffffffMundane grade Celestial Child. Requires 0 or more Growth Points. \r^8080ffRoyal grade Celestial Child. Required Growth Point: %d\r^aa32ffImperial grade Celestial Child. Required Growth Point: %d\r^ffdc50Sacred grade Celestial Child. Required Growth Points: %d",
	18461: "Drag here to refund Potential",
	18462: "Reward",
	18463: "Owned Celestial Infant",
	18464: "Name cannot be left blank",
	18465: "Not Learned",
	18466: "This action is unavailable during Celestial Incarnation",
	18467: "^FFAD00%s^FFFFFF has completed 15 days of Cultivation, and will awaken as a Celestial Child!",
	18468: "Starting a New Day will increases Zenith Pool EXP by 1",
	18469: "Guard's class skill gives them a higher chance to gain a lot of Growth Points when Tutoring.",
	18470: "Each Arcane Academy Cultivation Trait is powerful, but they will have negative effects if unlocked together.",
	18471: "Then Neverfall Cultivation Traits are at highest star grade, they will trigger additional Bond effects.",
	18472: "An Infant's Cultivation Period lasts 15 days",
	18473: "If you can collect all Cultivation Traits from Morai, you will trigger a very powerful Bond effect.",
	18474: "Collecting all Tideswell and Archosaur Cultivation Traits will increase the Growth Point of all Cultivation Traits in the Spirit Branch.",
	18475: "When Tutoring is completed every day, nothing more can be done.",
	18476: "Prophet's Cultivation Traits can be coupled with those from Glacier City or Cxi to gain better Bond effects.",
	18477: "Cultivation Traits have different place of origin and classes. Try different combinations to trigger different Bond effects.",
	18480: "This Celestial Child has reached highest grade! The overflowing ^FFAD00 %d ^FFFFFF Revelation Points have been converted into Crystal Extract and stored in the Crystal Extract Safe.",
	18481: "No Shortcut Set",
	18482: "Current Grade Level Cap: %d",
	18483: "Potential gained today: %d/%d\rPotential will be cleared per day at 24:00\rClick to path to ^ff0000Potential Agent Greencko",
	18484: "Potential Gained: %d",
	18485: "Not Acquainted"
	}